# Generated by Django 6.0.7 on 2026-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='selected_docs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
